BEGIN
	CREATE TABLE Users(
		ID INT IDENTITY PRIMARY KEY,

		Username VARCHAR(100) UNIQUE NOT NULL,
		Email VARCHAR(100) UNIQUE NOT NULL,
		PasswordHash VARCHAR(256) NOT NULL,
		Salt VARCHAR(256) NOT NULL,

		Name VARCHAR(100) CHECK (LEN(Name) > 2) NOT NULL,
		Phone1 VARCHAR(19),
		Phone2 VARCHAR(19),

		CreationDate DATETIME DEFAULT GETDATE(),
		LastLoginDate DATETIME
	);

	CREATE TABLE Hotels(
		ID INT IDENTITY PRIMARY KEY,
		Name VARCHAR(150) NOT NULL,
		Location VARCHAR(255) NOT NULL,
		Rooms INT NOT NULL
	);

	CREATE TABLE Bookings(
		ID INT IDENTITY PRIMARY KEY,

		CheckIn DATETIME NOT NULL,
		CheckOut DATETIME NOT NULL,

		UserID INT NOT NULL,
		HotelID INT NOT NULL,
		
		CONSTRAINT FK_Bookings_Hotels FOREIGN KEY (HotelID) REFERENCES Hotels(ID),
		CONSTRAINT FK_Bookings_Users FOREIGN KEY (UserID) REFERENCES Users(ID)
	);

	CREATE TABLE CalendarBlocks(
		ID INT IDENTITY PRIMARY KEY,

		DateIn DATETIME NOT NULL,
		DateOut DATETIME NOT NULL,

		HotelID INT NOT NULL,

		CONSTRAINT FK_CalendarBlocks_Hotels FOREIGN KEY (HotelID) REFERENCES Hotels(ID)
	);

	CREATE TABLE SupportMessages(
		ID INT IDENTITY PRIMARY KEY,

		UserID INT NOT NULL,
		HotelID INT NOT NULL,

		Message VARCHAR(500),

		CreatedDate DATETIME DEFAULT GETDATE(),

		CONSTRAINT FK_SupportMessages_Users FOREIGN KEY (UserID) REFERENCES Users(ID),
		CONSTRAINT FK_SupportMessages_Hotels FOREIGN KEY (HotelID) REFERENCES Hotels(ID)
	);
END;
GO